export class CreateLeadDto {
  tenantId?: string;
  salespersonId?: string;
  created_by?: string;
  company?: string;
  firstName?: string;
  lastName?: string;
  title?: string;
  email?: string;
  phone?: string;
  fax?: string;
  mobile?: string;
  website?: string;
  leadSource?: string;
  leadStatus?: string;
  industry?: string;
  noOfEmployees?: string;
  annualRevenue?: string;
  rating?: string;
  emailOptOut?: number;
  secondaryEmail?: string;
  twitter?: string;
  street?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
  description?: string;
}
